name: Docker Build & Push
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            outcastveron/fiveserver:latest
            outcastveron/fiveserver:${{ github.sha }}
          secrets: |
            "username=${{ secrets.DOCKERHUB_USERNAME }}"
            "password=${{ secrets.DOCKERHUB_TOKEN }}"
